source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"
inhibit_all_warnings!

pod 'AFNetworking', :git => 'git@github.com:AFNetworking/AFNetworking.git', :commit => '2abde225d990e9df924b996e53b83a7aa3aad1c0'